version: "3.6"

services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: dshop-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    image: postgres:alpine
    container_name: dshop-db
    environment:
      POSTGRES_USER: dshop
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  server:
    env_file: .env
    build:
      context: ./
    container_name: dshop-server
    working_dir: /usr/src/app
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: ${API_HOST}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_HOST: ${CLIENT_HOST}
    volumes:
      - ./server:/usr/src/app
    tty: true
    stdin_open: true

  client:
    image: node:alpine
    container_name: dshop-client
    working_dir: /usr/src/app
    user: node
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: ${CLIENT_HOST}
      REACT_APP_API_BASE_URL: ${API_BASE_URL}
    volumes:
      - ./client:/usr/src/app
    tty: true
    stdin_open: true
